version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/scaling
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Confige gcloud
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project dev-qlik-core
            gcloud --quiet config set compute/zone europe-west2-a
      - run:
          name: Accept EULA
          command: grep -rl AcceptEULA ./qlik-core | xargs sed -i 's/AcceptEULA=no/AcceptEULA=yes/g'
      - run:
          name: Set Disk Name For Test Cluster
          command: grep -rl my-disk ./nfs-volumes | xargs sed -i "s/my-disk/$DISK_NAME_TEST-$CIRCLE_BUILD_NUM/g"
      - run:
          name: Deploy test cluster
          environment:
            GCLOUD_NUM_NODES: 2
          command: K8S_CLUSTER=cci-cluster-$CIRCLE_BUILD_NUM DISK_NAME=$DISK_NAME_TEST-$CIRCLE_BUILD_NUM ./run.sh deploy
# Create and run test to validate app is working
      - run:
          name: Remove test cluster
          command: K8S_CLUSTER=cci-cluster-$CIRCLE_BUILD_NUM DISK_NAME=$DISK_NAME_TEST-$CIRCLE_BUILD_NUM ./run.sh remove
      - run:
          name: Set Disk Name For Live Cluster
          command: grep -rl $DISK_NAME_TEST-$CIRCLE_BUILD_NUM ./nfs-volumes | xargs sed -i "s/$DISK_NAME_TEST-$CIRCLE_BUILD_NUM/$DISK_NAME_PROD/g"
      - run:
          name: Deploy qlik-core scaling example if on master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              gcloud --quiet container clusters get-credentials core-scaling
              ./run.sh update
            fi
