version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/scaling
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY_TEST > ${HOME}/gcloud-service-key.json
      - run:
          name: Confige gcloud
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project dev-qlik-core
            gcloud --quiet config set compute/zone europe-west1-b
            gcloud --quiet container clusters get-credentials cci-test-cluster	
      - run:
          name: Accept EULA
          command: grep -rl AcceptEULA ./qlik-core | xargs sed -i 's/AcceptEULA=no/AcceptEULA=yes/g'
      - run:
          name: deploy qlik-core scaling example
          command: ./run.sh update
   
