kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |
    apiVersion: 1

    deleteDatasources:
      - name: Prometheus
        orgId: 1

    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus.monitoring.svc:9090
      isDefault: true
      version: 1
      editable: true
