apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.engine.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.engine.name }}
    helm.sh/chart: {{ include "qlik-core.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.engine.service.type }}
  {{- with .Values.engine.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.engine.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
