apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.qix.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.qix.name }}
    helm.sh/chart: {{ include "qlik-core.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.qix.port }}
      targetPort: {{ .Values.qix.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.qix.name }}
