apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: engine
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: engine
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metricName: qix_active_sessions
      targetAverageValue: 250
