apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-service
  labels:
    app: license-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-service
  template:
    metadata:
      labels:
        app: license-service
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: license-service
        image: "qlikcore/licenses:1.1.4"
        resources:
            requests:
              memory: "16Mi"
            limits:
              memory: "16Mi"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
        env:
        - name: LICENSES_SERIAL_NBR
          valueFrom:
            secretKeyRef:
              name: license-data
              key: LICENSES_SERIAL_NBR
        - name: LICENSES_CONTROL_NBR
          valueFrom:
            secretKeyRef:
              name: license-data
              key: LICENSES_CONTROL_NBR
      imagePullSecrets:
      - name: dockerhub
