apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: license-service
  labels:
    app: license-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: license-service
    spec:
      containers:
      - name: license-service
        image: "qlikcore/licenses:1.0.7"
        resources:
            requests:
              memory: "16Mi"
            limits:
              memory: "16Mi"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
        env:
        - name: LICENSES_SERIAL_NBR
          valueFrom:
            configMapKeyRef:
              name: license-data
              key: LICENSES_SERIAL_NBR
        - name: LICENSES_CONTROL_NBR
          valueFrom:
            configMapKeyRef:
              name: license-data
              key: LICENSES_CONTROL_NBR
      imagePullSecrets:
      - name: dockerhub
