apiVersion: apps/v1
kind: Deployment
metadata:
  name: mira
  labels:
    app: mira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mira
  template:
    metadata:
      labels:
        app: mira
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: mira
        resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "200Mi"
        image: "qlikcore/mira:2.0.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9100
        env:
        - name: MIRA_MODE
          value: kubernetes
        - name: MIRA_ENGINE_UPDATE_INTERVAL
          value: "5000"
      imagePullSecrets:
      - name: dockerhub
