apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine
  labels:
    app: engine
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: engine
        qix-engine: ""
    spec:
      containers:
      - name: engine
        image: qlikea/engine:12.136.0
        imagePullPolicy: IfNotPresent
        args: ["-S", "AcceptEULA=no" ] # change to 'yes' if you accept the Qlik Core EULA
        ports:
        - containerPort: 9076
        - containerPort: 9090
        volumeMounts:
        - name: doc-volume
          mountPath: /doc
        - name: data-volume
          mountPath: /data
      volumes:
      - name: doc-volume
        hostPath:
          path: /home/docker/doc
      - name: data-volume
        hostPath:
          path: /home/docker/csv
      imagePullSecrets:
      - name: dockerhub
