apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "nfs.fullname" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"
